### ISSUE TITLE
LedgerNano Error: User interaction is not allowed

### ISSUE THREAD

**Issue by kalpatech-team** [cosmos/gaia#766]
## Summary of Bug
Cannot sign / vote / add keys using a Ledger device

## Version
gaiad version v4.1.0

## Steps to Reproduce
1. gaiad keys add <key_name> --ledger
2. confirm address on Ledger device
3. Error: User interaction is not allowed. (-25308)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alessio** [comment]
Hi! What operating system are you experiencing this issue with?

**Comment by kalpatech-team** [comment]
macOS Big Sur & macOS Catalina

**Comment by alessio** [comment]
What's ledger firmware's version?

**Comment by gsora** [comment]
I wonder if this might be already fixed by [this Cosmos SDK PR](https://github.com/cosmos/cosmos-sdk/pull/8826).

**Comment by kalpatech-team** [comment]
> What's ledger firmware's version?

v1.6.1

**Comment by kalpatech-team** [comment]
manage to make it work only on macOS Catalina with latest go version ... with BigSur still not working

**Comment by tac0turtle** [comment]
I have used ledger with all updated macOS. Are you still running into this issue?

Ill close this for now, but feel free to comment or ping marbar in discord
